api_platform:
    title: 'HACKATHON 2022'
    description: 'hackathon 2022 - api platform'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
